### ISSUE TITLE
PORT environment variable seems not to exist while generating config

### ISSUE THREAD

**Issue by bdudelsack** [paketo-buildpacks/php-web#41]
I'm trying to build a PHP application with following configuration:

**buildpack.yml**
```
php:
  version: 7.2.*
  webserver: nginx
  webdirectory: htdocs
  libdirectory: library
composer:
  install_options: []
```
with this command:

```
pack build myapplication \
  --builder gcr.io/paketo-buildpacks/builder:full-cf
```

The image is getting build but cannot be started because of the corrupt nginx.conf.

```
2020/06/26 12:39:45 [emerg] 22#0: host not found in "default_server" of the "listen" directive in /workspace/nginx.conf:135
process nginx exited, status: exit status 1
```

Here is the corresponding part from the nginx.conf:

```
    server {
        listen         default_server;
        server_name localhost;

        fastcgi_temp_path      /tmp/nginx_fastcgi 1 2;
        client_body_temp_path  /tmp/nginx_client_body 1 2;
        proxy_temp_path        /tmp/nginx_proxy 1 2;
```

The port number ist no being written to the config. I have the same problem with "php-server". Tried adding `--env PORT=8080` to the command but it does not help.
